### ISSUE TITLE
Does example 3 work?

### ISSUE THREAD

**Issue by pme123** [Kremlianski/scalajs-sortable-demos#1]
I want to use drag functionality, like described in example 3. I tried your example, but the functions:
`val put: js.Function1[Sortable, js.Any]` and `val pull: js.Function2[Sortable, Sortable, js.Any]` are not called at all (I added println).

In the code there is this line:
    //only with 1.5.0

As the dependency is 1.4.2 I am not sure if this is the problem.

Is there a way to make this work?

**Comment by Kremlianski** [comment]
Sortable.js is constantly under development. It's functionality varies from version to version.
If you look at this official demo: http://jsbin.com/rusuvot/edit?js,output , you can see that it doesn't work.
But in 1.6.0 it works again (with questions).
I fixed it for 1.6.0. See http://projects.scalapro.net/sortable-js-facade/
This version is not in webjars yet. So you can't use it as dependency in sbt. You should use:
 <script src="//cdnjs.cloudflare.com/ajax/libs/Sortable/1.6.0/Sortable.min.js"></script>
instead in html
